apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - frontend/deployment.yaml
  - backend/deployment.yaml
  - payment/deployment.yaml
  - search/deployment.yaml
  - cart/deployment.yaml
  - product/deployment.yaml
  - api/deployment.yaml
  - ingress/ingress.yaml
