#!/usr/bin/env bash
#
# Render SSM Parameter Store values into the on-host environment file used by
# docker-compose.prod.yml.
#
#   AWS SSM Parameter Store  (/ecommerce/*)
#             |
#             v
#   /opt/ecommerce/.env.production   (mode 600, root/deploy owned, never committed)
#             |
#             v
#   docker compose env_file  ->  payment container
#
# Security rules enforced here:
#   * secret VALUES are never printed, not even with -x tracing enabled
#   * the generated file is written with umask 077 and atomically renamed
#   * the file is listed in .gitignore and must never be committed
#   * only parameters under the configured prefix are read (least privilege
#     matches the instance IAM policy)
#
# Usage:
#   scripts/aws/load-ssm-env.sh                     # render the file
#   scripts/aws/load-ssm-env.sh --list              # print parameter NAMES only
#   scripts/aws/load-ssm-env.sh --prefix /ecommerce/ --output /opt/ecommerce/.env.production
#
set -euo pipefail

PREFIX="${SSM_PARAMETER_PREFIX:-/ecommerce/}"
OUTPUT_FILE="${ECOMMERCE_ENV_FILE:-/opt/ecommerce/.env.production}"
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-}}"
MODE="render"

log()  { printf '[load-ssm-env] %s\n' "$*" >&2; }
die()  { printf '[load-ssm-env] ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --list)   MODE="list" ;;
    --render) MODE="render" ;;
    --prefix) PREFIX="${2:?--prefix needs a value}"; shift ;;
    --output) OUTPUT_FILE="${2:?--output needs a value}"; shift ;;
    --region) REGION="${2:?--region needs a value}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
  shift
done

command -v aws >/dev/null 2>&1 || die "aws CLI is not installed"
command -v jq  >/dev/null 2>&1 || die "jq is not installed"

case "$PREFIX" in
  /ecommerce/|/ecommerce) ;;
  *) log "WARNING: prefix $PREFIX differs from the IAM-scoped /ecommerce/ namespace" ;;
esac

AWS_ARGS=(--recursive --with-decryption --output json)
[ -n "$REGION" ] && AWS_ARGS+=(--region "$REGION")

# --- Read every parameter under the prefix (paginated) -----------------------
# Values are captured into a shell variable and consumed by jq; they are never
# echoed. The temporary file gets 0600 immediately.
umask 077
RAW="$(mktemp)"
trap 'rm -f "$RAW"' EXIT

NEXT_TOKEN=""
PARAM_COUNT=0
while :; do
  if [ -n "$NEXT_TOKEN" ]; then
    aws ssm get-parameters-by-path --path "$PREFIX" "${AWS_ARGS[@]}" \
      --next-token "$NEXT_TOKEN" >> "$RAW"
  else
    aws ssm get-parameters-by-path --path "$PREFIX" "${AWS_ARGS[@]}" >> "$RAW"
  fi
  NEXT_TOKEN="$(jq -r '.NextToken // empty' "$RAW" | tail -n 1)"
  [ -z "$NEXT_TOKEN" ] && break
done

PARAM_COUNT="$(jq -r '.Parameters | length' "$RAW" | tail -n 1)"

if [ "${PARAM_COUNT:-0}" -eq 0 ]; then
  die "no parameters found under $PREFIX. Run the bootstrap in README.md first."
fi

# --- Derive FOO_BAR from /ecommerce/foo-bar ---------------------------------
# Only the NAME is logged; values never reach stdout/stderr.
render() {
  jq -r --arg prefix "$PREFIX" '
    .Parameters[]
    | (.Name | ltrimstr($prefix))
    | ascii_downcase
    | gsub("[^a-z0-9]+"; "_")
    | gsub("^_+"; "")
    | gsub("_+$"; "")
    | ascii_upcase
  ' "$RAW" | sort -u
}

if [ "$MODE" = "list" ]; then
  log "$PARAM_COUNT parameter(s) available under $PREFIX (names only):"
  render | sed 's/^/  /'
  exit 0
fi

REQUIRED="ADMIN_USERNAME ADMIN_PASSWORD_HASH ADMIN_SESSION_SECRET PUBLIC_BASE_URL VODAFONE_CASH_NUMBER"
AVAILABLE=" $(render | tr '\n' ' ') "
MISSING=""
for key in $REQUIRED; do
  case "$AVAILABLE" in
    *" $key "*) ;;
    *) MISSING="$MISSING $key" ;;
  esac
done

TMP_FILE="$(mktemp "$(dirname "$OUTPUT_FILE")/.env.production.XXXXXX")"
{
  printf '# Generated by scripts/aws/load-ssm-env.sh - DO NOT COMMIT, DO NOT EDIT BY HAND.\n'
  printf '# Source: SSM Parameter Store %s\n' "$PREFIX"
  printf '# Regenerate: scripts/aws/load-ssm-env.sh\n'
  # The parameter object has to be bound BEFORE the name is rewritten into an
  # env-var key. Otherwise `as $key` runs after the pipeline has already reduced
  # each entry to a string, and `.Value` is then evaluated against that string:
  #
  #   jq: error (at ...): Cannot index string with string "Value"
  #
  # which made this generator exit 5, leaving .env.production unwritten and the
  # deploy failing with "SSM parameter load failed". Reproduced against jq-1.8.1.
  #
  # The final ascii_upcase implements the documented naming rule
  # (docs/AWS_FREE_TIER_DEPLOYMENT.md#parameter-store):
  #
  #   /ecommerce/public-base-url  ->  PUBLIC_BASE_URL
  #
  # It must run AFTER the gsub sanitisation, because gsub only tolerates the
  # lower-case class. Without it the file was written as `public_base_url=...`,
  # so deploy.sh's `grep -E '^PUBLIC_BASE_URL='` matched nothing and the
  # containers received no configuration at all.
  jq -r --arg prefix "$PREFIX" '
    .Parameters[]
    | . as $p
    | (
        $p.Name | ltrimstr($prefix)
                | ascii_downcase
                | gsub("[^a-z0-9]+"; "_")
                | gsub("^_+"; "")
                | gsub("_+$"; "")
      ) as $key
    | ($key | ascii_upcase) as $envkey
    | "\($envkey)=\($p.Value | tostring)"
  ' "$RAW"
} > "$TMP_FILE"

chmod 600 "$TMP_FILE"
mv -f "$TMP_FILE" "$OUTPUT_FILE"
chmod 600 "$OUTPUT_FILE"

log "wrote $PARAM_COUNT parameter(s) to $OUTPUT_FILE (mode 600)"
if [ -n "$MISSING" ]; then
  log "WARNING: recommended parameter(s) not set:$MISSING"
  log "         See docs/AWS_FREE_TIER_DEPLOYMENT.md#parameter-store"
fi
log "values were not printed and are not present in any log line."
