const nodemailer = require('nodemailer');

const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const amount = order => `${(order.amountCents / 100).toFixed(2)} ${order.currency}`;
function enabled(env = process.env) { return env.EMAIL_NOTIFICATIONS_ENABLED === 'true'; }
function transport(env = process.env) { return nodemailer.createTransport({ host: env.SMTP_HOST, port: Number(env.SMTP_PORT || 465), secure: env.SMTP_SECURE !== 'false', auth: { user: env.SMTP_USER, pass: env.SMTP_PASS }, connectionTimeout: 8000, greetingTimeout: 8000, socketTimeout: 12000 }); }
function rows(order) { return order.items.map(item => `<tr><td>${escape(item.name)}</td><td>${item.quantity}</td><td>${escape((item.unitPriceCents / 100).toFixed(2))}</td><td>${escape(((item.unitPriceCents * item.quantity) / 100).toFixed(2))}</td></tr>`).join(''); }
function created(order, env = process.env) { const admin = `${env.PUBLIC_BASE_URL || 'http://localhost:8088'}/admin`; const text = `Order ${order.orderId}\nCustomer: ${order.customer.fullName}\nPhone: ${order.customer.phone}\nAddress: ${order.customer.shippingAddress}, ${order.customer.city}\nTotal: ${amount(order)}\nPayment: Vodafone Cash\nStatus: Awaiting Payment\nAdmin: ${admin}`; return { subject: `New Order - ${order.orderId}`, text, html: `<main style="max-width:640px;margin:auto;font-family:Arial;color:#10243e"><h1 style="background:#10243e;color:#5eead4;padding:22px">NORTHSTAR • New order</h1><p><b>Order:</b> ${escape(order.orderId)}</p><p><b>Customer:</b> ${escape(order.customer.fullName)} · ${escape(order.customer.phone)}</p><p><b>Address:</b> ${escape(order.customer.shippingAddress)}, ${escape(order.customer.city)}</p><table style="width:100%;border-collapse:collapse"><thead><tr><th align="left">Product</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>${rows(order)}</tbody></table><h2>Total: ${escape(amount(order))}</h2><p>Payment: Vodafone Cash · Status: Awaiting Payment</p><p><a href="${escape(admin)}">Open Admin Dashboard</a></p></main>` }; }
function receipt(order, env = process.env) { const admin = `${env.PUBLIC_BASE_URL || 'http://localhost:8088'}/admin`; const text = `Payment Receipt Submitted - ${order.orderId}\nCustomer: ${order.customer.fullName}\nTotal: ${amount(order)}\nTransfer phone: ${order.transferPhone}\nReference: ${order.transactionReference || '-'}\nStatus: Receipt submitted\nAdmin: ${admin}`; return { subject: `Payment Receipt Submitted - ${order.orderId}`, text, html: `<main style="max-width:640px;margin:auto;font-family:Arial;color:#10243e"><h1 style="background:#10243e;color:#5eead4;padding:22px">NORTHSTAR • Receipt submitted</h1><p>Order <b>${escape(order.orderId)}</b> has a receipt awaiting review.</p><p><b>Customer:</b> ${escape(order.customer.fullName)}<br><b>Total:</b> ${escape(amount(order))}<br><b>Transfer phone:</b> ${escape(order.transferPhone)}<br><b>Reference:</b> ${escape(order.transactionReference || '-')}</p><p><a href="${escape(admin)}">Open Admin Dashboard</a></p></main>` }; }
async function send(order, event, env = process.env, makeTransport = transport) { if (!enabled(env)) { console.info('Order email notification skipped in local mode.'); return { status: 'skipped' }; } if (![env.ORDER_NOTIFICATION_EMAIL, env.SMTP_HOST, env.SMTP_USER, env.SMTP_PASS, env.EMAIL_FROM].every(Boolean)) throw new Error('Email notification configuration is incomplete'); const message = event === 'receipt_submitted' ? receipt(order, env) : created(order, env); await makeTransport(env).sendMail({ from: env.EMAIL_FROM, to: env.ORDER_NOTIFICATION_EMAIL, ...message }); return { status: 'sent' }; }
module.exports = { send, created, receipt, escape, enabled };
